#!/bin/bash

# Setting component name and path based on the directory name
component_name="$(basename "$(dirname "$(readlink -f "${BASH_SOURCE[0]}")")")"
config="/app/retrodeck/components/$component_name/rd_config"

# TODO: do a proper script
# This is just a placeholder script to test the emulator's flow
log i "----------------------"
log i "Preparing $component_name"
log i "----------------------"

# TODO: probably some of these needs to be put elsewhere
create_dir "$rd_home_saves_path/mame-sa"
create_dir "$rd_home_saves_path/mame-sa/nvram"
create_dir "$rd_home_states_path/mame-sa"
create_dir "$rd_home_screenhots_path/mame-sa"
create_dir "$rd_home_saves_path/mame-sa/diff"

create_dir "$XDG_CONFIG_HOME/mame/ctrlr"
create_dir "$XDG_CONFIG_HOME/mame/ini"
create_dir "$XDG_CONFIG_HOME/mame/cfg"
create_dir "$XDG_CONFIG_HOME/mame/inp"

create_dir "$rd_home_storage_path/mame/plugin-data"
create_dir "$rd_home_storage_path/mame/hash"
create_dir "$rd_home_bios_path/mame-sa/samples"
create_dir "$rd_home_storage_path/mame/assets/artwork"
create_dir "$rd_home_storage_path/mame/assets/fonts"
create_dir "$rd_home_storage_path/mame/assets/crosshair"
create_dir "$rd_home_storage_path/mame/plugins"
create_dir "$rd_home_storage_path/mame/assets/language"
create_dir "$rd_home_storage_path/mame/assets/software"
create_dir "$rd_home_storage_path/mame/assets/comments"
create_dir "$rd_home_storage_path/mame/assets/share"
create_dir "$rd_home_storage_path/mame/dats"
create_dir "$rd_home_storage_path/mame/folders"
create_dir "$rd_home_storage_path/mame/assets/cabinets"
create_dir "$rd_home_storage_path/mame/assets/cpanel"
create_dir "$rd_home_storage_path/mame/assets/pcb"
create_dir "$rd_home_storage_path/mame/assets/flyers"
create_dir "$rd_home_storage_path/mame/assets/titles"
create_dir "$rd_home_storage_path/mame/assets/ends"
create_dir "$rd_home_storage_path/mame/assets/marquees"
create_dir "$rd_home_storage_path/mame/assets/artwork-preview"
create_dir "$rd_home_storage_path/mame/assets/bosses"
create_dir "$rd_home_storage_path/mame/assets/logo"
create_dir "$rd_home_storage_path/mame/assets/scores"
create_dir "$rd_home_storage_path/mame/assets/versus"
create_dir "$rd_home_storage_path/mame/assets/gameover"
create_dir "$rd_home_storage_path/mame/assets/howto"
create_dir "$rd_home_storage_path/mame/assets/select"
create_dir "$rd_home_storage_path/mame/assets/icons"
create_dir "$rd_home_storage_path/mame/assets/covers"
create_dir "$rd_home_storage_path/mame/assets/ui"
create_dir "$rd_home_shaders_path/mame/bgfx/"
create_dir "$XDG_DATA_HOME/mame/plugin-data"
create_dir "$XDG_DATA_HOME/mame/hash"
create_dir "$XDG_DATA_HOME/mame/assets/artwork"
create_dir "$XDG_DATA_HOME/mame/assets/fonts"
create_dir "$XDG_DATA_HOME/mame/assets/crosshair"
create_dir "$XDG_DATA_HOME/mame/plugins"
create_dir "$XDG_DATA_HOME/mame/assets/language"
create_dir "$XDG_DATA_HOME/mame/assets/software"
create_dir "$XDG_DATA_HOME/mame/assets/comments"
create_dir "$XDG_DATA_HOME/mame/assets/share"
create_dir "$XDG_DATA_HOME/mame/dats"
create_dir "$XDG_DATA_HOME/mame/folders"
create_dir "$XDG_DATA_HOME/mame/assets/cabinets"
create_dir "$XDG_DATA_HOME/mame/assets/cpanel"
create_dir "$XDG_DATA_HOME/mame/assets/pcb"
create_dir "$XDG_DATA_HOME/mame/assets/flyers"
create_dir "$XDG_DATA_HOME/mame/assets/titles"
create_dir "$XDG_DATA_HOME/mame/assets/ends"
create_dir "$XDG_DATA_HOME/mame/assets/marquees"
create_dir "$XDG_DATA_HOME/mame/assets/artwork-preview"
create_dir "$XDG_DATA_HOME/mame/assets/bosses"
create_dir "$XDG_DATA_HOME/mame/assets/logo"
create_dir "$XDG_DATA_HOME/mame/assets/scores"
create_dir "$XDG_DATA_HOME/mame/assets/versus"
create_dir "$XDG_DATA_HOME/mame/assets/gameover"
create_dir "$XDG_DATA_HOME/mame/assets/howto"
create_dir "$XDG_DATA_HOME/mame/assets/select"
create_dir "$XDG_DATA_HOME/mame/assets/icons"
create_dir "$XDG_DATA_HOME/mame/assets/covers"
create_dir "$XDG_DATA_HOME/mame/assets/ui"
create_dir "$rd_home_cheats_path/mame/cheat"

dir_prep "$rd_home_saves_path/mame-sa/hiscore" "$XDG_CONFIG_HOME/mame/hiscore"

cp -fvr "$config/mame.ini" "$mame_config"
cp -fvr "$config/ui.ini" "$" "$mame_ui_config"
cp -fvr "$config/default.cfg" "$mame_default_config"
cp -fvr "/app/retrodeck/components/mame/share/mame/bgfx/"* "$rd_home_shaders_path/mame/bgfx"

sed -i 's#RETRODECKROMSDIR#'"$rd_home_roms_path"'#g' "$mame_config" # one-off as roms folders are a lot
set_setting_value "$mame_config" "nvram_directory" "$rd_home_saves_path/mame-sa/nvram" "mame"
set_setting_value "$mame_config" "state_directory" "$rd_home_states_path/mame-sa" "mame"
set_setting_value "$mame_config" "snapshot_directory" "$rd_home_screenshots_path/mame-sa" "mame"
set_setting_value "$mame_config" "diff_directory" "$rd_home_saves_path/mame-sa/diff" "mame"
set_setting_value "$mame_config" "samplepath" "$rd_home_bios_path/mame-sa/samples" "mame"
set_setting_value "$mame_config" "cheatpath" "$rd_home_cheats_path/mame" "mame"
set_setting_value "$mame_config" "bgfx_path" "$rd_home_shaders_path/mame/bgfx/" "mame"

log i "Placing cheats in \"$rd_home_cheats_path/mame\""
unzip -j -o "$config/cheat0264.zip" 'cheat.7z' -d "$rd_home_cheats_path/mame"
