- source:
    type: key
    data:
      keycode: 16777264
  target: 164
- source:
    type: key
    data:
      keycode: 16777265
  target: 165
- source:
    type: key
    data:
      keycode: 16777266
  target: 180
- source:
    type: key
    data:
      keycode: 16777267
  target: 181
- source:
    type: key
    data:
      keycode: 16777220
  target: 167
- source:
    type: key
    data:
      keycode: 16777235
  target: 16
- source:
    type: key
    data:
      keycode: 16777237
  target: 17
- source:
    type: key
    data:
      keycode: 16777234
  target: 14
- source:
    type: key
    data:
      keycode: 16777236
  target: 15
- source:
    type: key
    data:
      keycode: 48
  target: 48
- source:
    type: key
    data:
      keycode: 49
  target: 49
- source:
    type: key
    data:
      keycode: 50
  target: 50
- source:
    type: key
    data:
      keycode: 51
  target: 51
- source:
    type: key
    data:
      keycode: 52
  target: 52
- source:
    type: key
    data:
      keycode: 53
  target: 53
- source:
    type: key
    data:
      keycode: 54
  target: 54
- source:
    type: key
    data:
      keycode: 55
  target: 55
- source:
    type: key
    data:
      keycode: 56
  target: 56
- source:
    type: key
    data:
      keycode: 57
  target: 57
- source:
    type: key
    data:
      keycode: 42
  target: 42
- source:
    type: key
    data:
      keycode: 47
  target: 127
- source:
    type: key
    data:
      keycode: 16777219
  target: 1